"""Parse the three "master document" attachments the school posts once per
academic year: the Holiday List, the Special Days & Events list, and the
class Time Table.

Unlike Subject Notes / portion-sheet attachments -- scanned photos, see
docs/portion_schedules.json, hand-typed for that reason -- these three are
genuine text-layer PDFs generated by the same templated system, confirmed
by pulling real examples and checking for an extractable text layer. So
their tables can be parsed directly with pypdf/pdfplumber, no OCR needed.

Detection runs on the notice's own SMS-style text (cheap, no download
needed) before deciding whether to fetch and parse the attachment.
"""

import re
from datetime import date
from io import BytesIO
from typing import Optional

import pdfplumber
from pypdf import PdfReader

from classifier.classify import _MONTHS

HOLIDAY_LIST = "holiday_list"
EVENTS_LIST = "events_list"
TIMETABLE = "timetable"

_HOLIDAY_LIST_RE = re.compile(r"holiday\s*list|list\s*of\s*holidays", re.I)
_EVENTS_LIST_RE = re.compile(r"special\s*days\s*(?:&|and)\s*events", re.I)
# A daily/forward timetable notice always names a specific date right after
# "timetable for" (e.g. "for 7th April 2026, Tuesday"); the once-a-year
# master timetable never does ("...for your ward for AY 2026-27", "Sharing
# the class Timetable.") -- that's the only reliable discriminator, since
# both share overlapping "sharing the timetable..." phrasing.
_TIMETABLE_RE = re.compile(r"\btime\s*table\b", re.I)
_DAILY_TIMETABLE_DATE_RE = re.compile(r"time\s*table\s*for\s*\d", re.I)


def detect(notice_text: str) -> Optional[str]:
    if _HOLIDAY_LIST_RE.search(notice_text):
        return HOLIDAY_LIST
    if _EVENTS_LIST_RE.search(notice_text):
        return EVENTS_LIST
    if _TIMETABLE_RE.search(notice_text) and not _DAILY_TIMETABLE_DATE_RE.search(notice_text):
        return TIMETABLE
    return None


def _pdf_text(pdf_bytes: bytes) -> str:
    reader = PdfReader(BytesIO(pdf_bytes))
    return "\n".join(page.extract_text() or "" for page in reader.pages)


def _month_index(name: str) -> int:
    return _MONTHS.index(name.lower()) + 1


_MONTH_RE = "|".join(_MONTHS)
_HOLIDAY_YEAR_RE = re.compile(r"^Year\s+(\d{4})$", re.I)
_HOLIDAY_ROW_RE = re.compile(r"^(\d{1,2})\s+(" + _MONTH_RE + r")\s+(\w+day)\s+(.+)$", re.I)
_VACATION_ROW_RE = re.compile(
    r"^(.+?Vacation)\s+(\d{1,2})\w*\s+(" + _MONTH_RE + r")\s+(\d{4}),\s*\w+day"
    r"\s+to\s+(\d{1,2})\w*\s+(" + _MONTH_RE + r")\s+(\d{4}),\s*\w+day",
    re.I,
)


def parse_holiday_list(pdf_bytes: bytes) -> dict:
    """List of holidays for AY <year> -- a per-calendar-year holiday table
    (the doc spans two calendar years) plus a Vacations block."""
    holidays, vacations = [], []
    year = None
    for line in _pdf_text(pdf_bytes).splitlines():
        line = line.strip()
        if not line:
            continue
        m = _HOLIDAY_YEAR_RE.match(line)
        if m:
            year = int(m.group(1))
            continue
        m = _HOLIDAY_ROW_RE.match(line)
        if m and year:
            day, month_name, weekday, name = m.groups()
            try:
                d = date(year, _month_index(month_name), int(day))
                holidays.append({"date_iso": d.isoformat(), "day": weekday, "name": name.strip()})
            except ValueError:
                pass
            continue
        m = _VACATION_ROW_RE.match(line)
        if m:
            name, d1, mo1, y1, d2, mo2, y2 = m.groups()
            try:
                start = date(int(y1), _month_index(mo1), int(d1))
                end = date(int(y2), _month_index(mo2), int(d2))
                if end < start:
                    # Seen for real: the source PDF's Christmas Vacation row
                    # says "...to 1st January 2026" when it means 2027 --
                    # a vacation can't end before it starts, so roll the
                    # end year forward rather than publish a bad range.
                    end = date(end.year + 1, end.month, end.day)
                vacations.append({"name": name.strip(), "start_iso": start.isoformat(), "end_iso": end.isoformat()})
            except ValueError:
                pass
    return {"holidays": holidays, "vacations": vacations}


_EVENTS_MONTH_HEADER_RE = re.compile(r"^(" + _MONTH_RE + r")\s+(\d{4})$", re.I)
_EVENTS_ROW_RE = re.compile(
    r"^(\d{1,2})(?:\s*[-–]\s*\d{1,2})?\s+(\w+day)(?:\s*[-–]\s*\w+day)?\s+(.+)$", re.I,
)
_EVENTS_SECTION_SKIP_RE = re.compile(r"^date\s+day\s+name\s+of\s+event$", re.I)
_PAGE_FOOTER_RE = re.compile(r"^\d+/\d+$")
_BARE_WEEKDAY_RE = re.compile(r"^\w+day$", re.I)
_PTM_HEADER_RE = re.compile(r"^Parent Teacher Meeting$", re.I)
_PTM_ROW_RE = re.compile(
    r"^(PTM-\d+|Term\s+\w+\s+Progress\s+Report)\s+(\d{1,2})\w*\s+(" + _MONTH_RE + r")\s+(\d{4})\s*(.*)$", re.I,
)
_EXAM_HEADER_RE = re.compile(r"^Exam\s*Schedule$", re.I)
_EXAM_SKIP_RE = re.compile(r"^assessment\s+date$", re.I)
_EXAM_ROW_RE = re.compile(
    r"^(.+?)\s+(\d{1,2})\w*\s+(" + _MONTH_RE + r")\s+(\d{4})\s*[-–]\s*"
    r"(\d{1,2})\w*\s+(" + _MONTH_RE + r")\s+(\d{4})$",
    re.I,
)


def parse_events_list(pdf_bytes: bytes) -> dict:
    """Special Days & Events for AY <year> -- three tables in one document:
    the special-days/events calendar, the Parent-Teacher Meeting schedule,
    and (per the user's observation that exam windows "will be in the
    events list pdf too") a high-level Exam Schedule of date ranges, not
    per-subject class-test dates."""
    lines = [ln.strip() for ln in _pdf_text(pdf_bytes).splitlines()]

    section = "events"
    events, ptm, exam_windows = [], [], []
    month, year = None, None
    # A multi-day event's date/weekday line can itself wrap across two PDF
    # text lines (e.g. "3 - 5 Thursday –" / "Saturday" / "Annual Day"), so
    # the date is tracked separately from whether a real event name has
    # been attached to it yet -- a continuation line only creates an event
    # once real name text shows up, not on the date/weekday fragments.
    pending_date_iso, pending_day = None, None

    for line in lines:
        if not line or _PAGE_FOOTER_RE.match(line):
            continue
        if _PTM_HEADER_RE.match(line):
            section = "ptm"
            continue
        if _EXAM_HEADER_RE.match(line):
            section = "exam"
            continue

        if section == "events":
            if _EVENTS_SECTION_SKIP_RE.match(line):
                continue
            m = _EVENTS_MONTH_HEADER_RE.match(line)
            if m:
                month, year = _month_index(m.group(1)), int(m.group(2))
                continue
            m = _EVENTS_ROW_RE.match(line)
            if m and month and year:
                day, weekday, name = m.groups()
                try:
                    d = date(year, month, int(day))
                except ValueError:
                    continue
                pending_date_iso, pending_day = d.isoformat(), weekday
                name = name.strip(" -–")
                if name:
                    events.append({"date_iso": pending_date_iso, "day": pending_day, "name": name})
                continue
            if _BARE_WEEKDAY_RE.match(line):
                # End weekday of a wrapped date range, e.g. "Saturday" on
                # its own line closing "3 - 5 Thursday –". Not a new event.
                pending_day = line
                continue
            # A continuation line with no leading date (a second event
            # sharing the prior line's date, the rest of a wrapped event
            # name, or a qualifying note like "(One of the days from the
            # dates given)") attaches to the pending date/event rather
            # than starting one blind.
            if pending_date_iso:
                if line.startswith("(") and events:
                    events[-1]["name"] = f"{events[-1]['name']} {line}"
                else:
                    events.append({"date_iso": pending_date_iso, "day": pending_day, "name": line})

        elif section == "ptm":
            m = _PTM_ROW_RE.match(line)
            if m:
                label, day, month_name, yr, scope = m.groups()
                try:
                    d = date(int(yr), _month_index(month_name), int(day))
                    ptm.append({"label": label.strip(), "date_iso": d.isoformat(), "scope": scope.strip() or None})
                except ValueError:
                    pass

        elif section == "exam":
            if _EXAM_SKIP_RE.match(line):
                continue
            m = _EXAM_ROW_RE.match(line)
            if m:
                name, d1, mo1, y1, d2, mo2, y2 = m.groups()
                try:
                    start = date(int(y1), _month_index(mo1), int(d1))
                    end = date(int(y2), _month_index(mo2), int(d2))
                    exam_windows.append({"name": name.strip(), "start_iso": start.isoformat(), "end_iso": end.isoformat()})
                except ValueError:
                    pass

    return {"events": events, "ptm": ptm, "exam_windows": exam_windows}


_TIMETABLE_PERIOD_CELL_RE = re.compile(r"^(\d+)\n(.+)$", re.DOTALL)


def parse_timetable(pdf_bytes: bytes) -> dict:
    """Class Time Table for AY <year> -- a ruled day/period grid, extracted
    via pdfplumber's table detection rather than plain text (a flattened
    text dump loses which subject belongs to which day/period column)."""
    with pdfplumber.open(BytesIO(pdf_bytes)) as pdf:
        table = pdf.pages[0].extract_table()
    if not table:
        return {"days": [], "periods": []}

    days = [d.strip() for d in table[0][1:] if d]
    periods = []
    for row in table[1:]:
        first = (row[0] or "").strip()
        m = _TIMETABLE_PERIOD_CELL_RE.match(first)
        if m:
            period_num, time_range = int(m.group(1)), m.group(2).replace("\n", " ").strip()
            label = None
        else:
            period_num, time_range = None, first.replace("\n", " ").strip()
            label = (row[1] or "").strip() or None

        if label:
            # A break/non-period row (Short Break, Long Break, Class
            # Teacher Period) -- same for every day, so no per-day split.
            periods.append({"period": period_num, "time": time_range, "break": label})
        else:
            by_day = {day: ((cell or "").replace("\n", " ").strip() or None) for day, cell in zip(days, row[1:])}
            periods.append({"period": period_num, "time": time_range, "subjects": by_day})

    return {"days": days, "periods": periods}


PARSERS = {
    HOLIDAY_LIST: parse_holiday_list,
    EVENTS_LIST: parse_events_list,
    TIMETABLE: parse_timetable,
}

OUTPUT_PATHS = {
    HOLIDAY_LIST: "docs/holidays.json",
    EVENTS_LIST: "docs/events_calendar.json",
    TIMETABLE: "docs/timetable.json",
}
